resolves #1133 ajout d'un bloc sens public dans le formulaire
EcrituresNumeriques/stylo pull request #1145
Opened 2024-12-10 16:23 UTC by ggrossetie

resolves #1133

2024-12-12 19:50 UTC, ggrossetie commented
@RochDLY Je te laisse voir sur la preview si ça te convient et peut être faire une relecture de la traduction des catégories.

2024-12-13 10:46 UTC, RochDLY requested changes

2024-12-13 10:46 UTC, RochDLY commented on front/src/locales/en/translation.json
> +  "article.metadata.senspublic.dossierSummary": "Dossier",
"article.metadata.senspublic.dossierSummary": "Issue summary",

2024-12-13 10:46 UTC, RochDLY commented on front/src/locales/fr/translation.json
> +  "article.metadata.senspublic.dossierSummary": "Dossier",
"article.metadata.senspublic.dossierSummary": "Sommaire du dossier",

2024-12-13 10:46 UTC, RochDLY commented on front/src/locales/en/translation.json
> +  "article.metadata.senspublic.editorialColumn": "Editorial column",
"article.metadata.senspublic.editorialColumn": "Chronicle",

2024-12-13 12:19 UTC, ggrossetie commented on front/src/locales/en/translation.json
> +  "article.metadata.senspublic.dossierSummary": "Dossier",
```suggestion
  "article.metadata.senspublic.dossierSummary": "Issue summary",
```

2024-12-13 12:20 UTC, ggrossetie commented on front/src/locales/en/translation.json
> +  "article.metadata.senspublic.editorialColumn": "Editorial column",
```suggestion
  "article.metadata.senspublic.editorialColumn": "Chronicle",
```

2024-12-13 12:20 UTC, ggrossetie commented on front/src/locales/fr/translation.json
> +  "article.metadata.senspublic.dossierSummary": "Dossier",
```suggestion
  "article.metadata.senspublic.dossierSummary": "Sommaire du dossier",
```

2024-12-13 12:22 UTC, ggrossetie commented
@RochDLY Tu peux faire des "suggestions", c'est assez pratique pour des petits changements. Cela me permet de faire un commit avec tes suggestions directement depuis GitHub.

2024-12-13 12:23 UTC, merged

2024-12-13 12:50 UTC, RochDLY commented
> @RochDLY Tu peux faire des "suggestions", c'est assez pratique pour des petits changements. Cela me permet de faire un commit avec tes suggestions directement depuis GitHub.

Ah justement ! J'ai cliqué sur l'autre en me disant que c'était l'un des deux qui permettait de faire ça, c'était donc une mauvaise pioche ! J'en prends bonne note pour les prochaines fois ! merci !