rename files with ArticleID for export by ArticleId
EcrituresNumeriques/stylo pull request #263
Opened 2020-10-21 19:48 UTC by lakonis

J'ai tenté qlq chose pour traiter #247

2020-10-22 08:21 UTC, Mogztter commented on export/src/export.js
> +      exportHTML({ bib: req.params.id.bib, yaml: req.params.id.yaml, md: req.params.id.md, id: req.params.id._id, title: article._doc.title }, res, req)
Le BibTeX, le YAML et le Markdown proviennent toujours de la dernière version de l'article, il faut donc conserver `cleanedVersion.bib`, `cleanedVersion.yaml` et `cleanedVersion.md`.

`req.params.id` contient l'identifiant de l'article (chaîne de caractères), il faut donc utiliser `id: req.params.id` et non `id: id: req.params.id._id`:


```suggestion
      exportHTML({ bib: cleanedVersion.bib, yaml: cleanedVersion.yaml, md: cleanedVersion.md, id: req.params.id, title: article._doc.title }, res, req)
```

2020-10-22 08:22 UTC, Mogztter commented on export/src/export.js
> +      exportZIP({ bib: req.params.id.bib, yaml: req.params.id.yaml, md: req.params.id.md, id: req.params.id._id, title: article._doc.title }, res, req)
Même remarque que plus haut ☝️

2020-10-22 08:23 UTC, Mogztter requested changes
Je te laisse corriger le code pour qu'il soit correct mais dans l'idée c'était ça :wink:

2020-10-22 12:45 UTC, lakonis commented on export/src/export.js
> +      exportZIP({ bib: req.params.id.bib, yaml: req.params.id.yaml, md: req.params.id.md, id: req.params.id._id, title: article._doc.title }, res, req)
done!

2020-10-22 12:47 UTC, lakonis commented
mais j'attire ton attention sur un autre bug #264 ...

2020-11-03 18:35 UTC, Mogztter commented
@lakonis Comme je me suis lancé dans la refonte du service d'export, j'ai inclus cette modification dans #266 

Une fois que #266 sera fusionné, est-ce que tu pourras s'il te plait faire des tests sur https://stylo-dev.huma-num.fr/ pour valider que cela fonctionne ?

2020-11-03 18:35 UTC, closed without merging