issue-505:Filter by tag ne s'affiche plus quand il n'y a pas de tag
EcrituresNumeriques/stylo pull request #506
Opened 2021-12-12 15:59 UTC by marieflorescontact

2021-12-13 18:12 UTC, oncletom commented
Le commit ajoute beaucoup de fichiers périphériques qui ne sont pas liés à la résolution du problème : 

- est-ce que le fichier `.gitignore` a été généré, ou c'est toi qui l'a construit "à la main" ?
- j'aurais tendance à ajouter `.idea` au `.gitignore` à la racine du dépôt, sauf s'il y a un intérêt à en versionner les fichiers (je ne connais pas assez pour me prononcer)
- est-ce que `volta` peut ne pas avoir à modifier le fichier `package.json` ? Sinon c'est pas grave.

2021-12-13 18:55 UTC, marieflorescontact commented
j'aurais peut être du pusher juste le fichier que j'ai modifié?
je n'ai pas touché au` .gitignore`, je l'ai laissé tel quel lors de l'install: est-ce que je dois le modifier?
Quant à `Volta` je ne crois pas qu'il soit nécessaire de l'inclure, je l'ai utilisé pour installer la bonne version de `node`.

2021-12-13 19:06 UTC, oncletom commented
> j'aurais peut être du pusher juste le fichier que j'ai modifié?

Je dirais qu'oui :) 

>  Quant à Volta je ne crois pas qu'il soit nécessaire de l'inclure, je l'ai utilisé pour installer la bonne version de node.

On spécifie déjà `engines.node` dans le ficheir package.json. [J'ai tendance à croire qu'en faisant `volta install`](https://docs.volta.sh/advanced/packages#pinned-node-version), il sait s'en débrouiller pour installer la version de Node adéquate au projet.

2021-12-13 20:23 UTC, Mogztter commented
> On spécifie déjà engines.node dans le fichier package.json. J'ai tendance à croire qu'en faisant volta install, il sait s'en débrouiller pour installer la version de Node adéquate au projet.

Je suis pas certain, je crois que dans les dernières versions il faut utiliser `volta pin` qui ajoute `volta` dans le `package.json`: https://docs.volta.sh/guide/understanding#managing-your-project

C'est un peu l'équivalent du `.nvmrc` sauf que la définition est dans le fichier `package.json`. L'auteur de Volta justifie le choix de ne pas utiliser `engines.node` ici : https://github.com/volta-cli/volta/issues/355#issuecomment-483880663

2021-12-13 20:24 UTC, Mogztter commented
> j'aurais tendance à ajouter .idea au .gitignore à la racine du dépôt, sauf s'il y a un intérêt à en versionner les fichiers (je ne connais pas assez pour me prononcer)

Je pense qu'on peut ajouter `.idea` dans le `.gitignore`

2021-12-14 09:33 UTC, Mogztter commented on front/src/components/Articles.jsx
> +      <h1>Articles for {displayName} </h1>
Ce changement n'est pas nécessaire : 

```suggestion
      <h1>Articles for {displayName}</h1>
```

2021-12-14 09:37 UTC, marieflorescontact commented on front/src/components/Articles.jsx
> +      <h1>Articles for {displayName} </h1>
ok

2021-12-14 09:39 UTC, marieflorescontact commented
comment je peux rattraper le fait d'avoir tout pushé au lieu d'avoir push seulement le fichier modifié?:grimacing:

2021-12-14 09:44 UTC, Mogztter commented on front/src/components/Articles.jsx
> +          }
Je pense que ça pourrait être bien d'encapsuler le titre et la liste dans un fragment React (https://reactjs.org/docs/fragments.html#short-syntax) et de conditionner l'affichage de ce "composant".

Quelque chose comme ça :

```jsx
{tags.length &&
<>
  <h4>Filter by Tags</h4>
  <ul className={styles.filterByTags}>
    {/* ... */}
  </ul>
</>}
```

Concernant la condition, on peut la simplifier en écrivant uniquement `tags.length` car la valeur de `length` est un nombre positif (et entier) et la valeur 0 est "falsy" : https://developer.mozilla.org/fr/docs/Glossary/Falsy.
Autrement dit, `tags.length` sera "true" quand la valeur est supérieure ou égale à 1.

2021-12-14 09:45 UTC, Mogztter requested changes

2021-12-14 09:45 UTC, Mogztter commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Comme mentionné dans les commentaires, il faut revert les fichiers `.idea/*` du commit et ajouter le dossier `/.idea/` dans le fichier `.gitignore`

2021-12-14 09:47 UTC, Mogztter commented
> comment je peux rattraper le fait d'avoir tout pushé au lieu d'avoir push seulement le fichier modifié?

Comme c'est le dernier commit, tu peux utiliser `git commit --amend` (https://git-scm.com/book/fr/v2/Utilitaires-Git-R%C3%A9%C3%A9crire-l%E2%80%99historique) ou alors faire des commits supplémentaires qui annule tes changements et ensuite faire un squash.

2021-12-14 19:54 UTC, marieflorescontact commented on front/src/components/Articles.jsx
> +          }
si j'écris ma condition sans l'opérateur de comparaison et que la `tags.length == 0`, j'ai un '0' qui s'affiche...

2021-12-14 20:30 UTC, Mogztter commented on front/src/components/Articles.jsx
> +          }
Ah, je pensais que ça fonctionnait désolé 😞 
Peut être qu'il faut faire `Boolean(tags.length)` pour que ça fonctionne mais ça perd complètement son intérêt... 

On peut garder `tags.length >= 1` c'est assez explicite.

2021-12-15 08:52 UTC, marieflorescontact commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
je crois que c'est fait (git=>:sweat_smile: )

2021-12-16 09:42 UTC, Mogztter approved these changes

2021-12-17 09:01 UTC, merged

2021-12-17 09:02 UTC, oncletom commented
🚀 

Merci @marieflorescontact et bravo pour ta première pull request sur Stylo 🙂