WIP - correction traduction by dans l'éditeur de texte
EcrituresNumeriques/stylo pull request #984
Opened 2023-11-30 15:34 UTC by RochDLY

2024-03-08 08:24 UTC, RochDLY commented
@ggrossetie @marviro si c'est bon pour vous je peux squash and merge ?

2024-03-08 08:39 UTC, marviro commented
> @ggrossetie @marviro si c'est bon pour vous je peux squash and merge ?
ok pour moi

2024-03-08 16:11 UTC, ggrossetie requested changes

2024-03-08 16:11 UTC, ggrossetie commented on front/src/components/Write/Versions.jsx
> +          {t('article.by.text')}
Il manque le nom de l'utilisateur non ?

2024-03-08 19:33 UTC, RochDLY commented on front/src/components/Write/Versions.jsx
> +          {t('article.by.text')}
Ah oui bien vu ! Je ne sais même pas pourquoi je l'avais retiré ... Par contre avec la syntaxe utilisée je ne sais pas où mettre les balises <strong>. Peut-être dans le JSON avec les clefs de trad autour de la variable {{owner}} ?

2024-03-09 09:19 UTC, ggrossetie commented on front/src/components/Write/Versions.jsx
> +          {t('article.by.text')}
Oui je pense que c'est OK

2024-03-09 09:20 UTC, ggrossetie commented
Il y a un soucis avec le build de l'export 🤔 
Est-ce que tu peux rebase sur master?

2024-03-11 08:30 UTC, RochDLY commented
> Il y a un soucis avec le build de l'export 🤔 Est-ce que tu peux rebase sur master?

Malgré le rebase il n'arrive toujours pas à construire l'export. :cry:

2024-10-09 07:16 UTC, ggrossetie commented
@RochDLY j'ai recrée la PR avec ton commit : https://github.com/EcrituresNumeriques/stylo/pull/1034

2024-10-09 07:16 UTC, closed without merging